wish: main.o cmdops.o error.o builtins.o paths.o
	gcc -o wish main.o cmdops.o error.o builtins.o paths.o

main.o: main.c
	gcc -c main.c

cmdops.o: cmdops.c 
	gcc -c cmdops.c

error.o: error.c 
	gcc -c error.c

builtins.o: builtins.c 
	gcc -c builtins.c

paths.o: paths.c
	gcc -c paths.c